#auto: true
#server: true
markdown: redcarpet

# Note: Github Pages runs with this command:
# jekyll --pygments --no-lsi --safe
pygments: true
lsi: false
safe: false

exclude: "node_modules/"

# Be sure to checkout the toolkitchen.github.com repo.
# This is where the generated docs are output.
#destination: ../test.github.com

# Site globals.
load_platform: true
project_title: Toolkitchen
