# Server defaults.
#watch: false # deprecated
#server: false # deprecated
#auto: true # deprecated
port: 4000

# Project defaults.
#markdown: redcarpet
markdown: kramdown
pygments: false
lsi: false
safe: false

exclude: ["node_modules", "README.md", "Gruntfile.js", "package.json"]

# Site globals used throughout docs.
load_platform: true
project_title: Polymer
