auto: true
server: true
markdown: redcarpet

# Github Pages runs with this command:
#jekyll --pygments --no-lsi --safe
pygments: true
safe: false
lsi: false

#exclude: ["README.md"]

# Site globals.
load_platform: true
project_title: Toolkitchen
