application: polymer-project
version: 2013-06-05
runtime: python27
api_version: 1
threadsafe: yes

#default_expiration: "0s"

handlers:

- url: /$
  static_files: _site/index.html
  upload: _site/index\.html

- url: /polymer
  static_dir: polymer

- url: /toolkit-ui
  static_dir: toolkit-ui

- url: /
  static_dir: _site

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^node_modules/.*